---
sidebar: sidebar 
permalink: technical-reports/ransomware-protection/index.html 
keywords: ransomware attacks, storagegrid, best practices 
summary: ランサムウェア攻撃と、StorageGRIDのセキュリティに関するベストプラクティスでデータを保護する方法をご紹介します。 
---
= StorageGRID S3オブジェクトをランサムウェアから保護
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
ランサムウェア攻撃と、StorageGRIDのセキュリティに関するベストプラクティスでデータを保護する方法をご紹介します。

ランサムウェア攻撃が増加しています。このドキュメントでは、StorageGRIDでオブジェクトデータを保護する方法について、いくつかの推奨事項を示します。

ランサムウェアは今日、データセンターに常に存在する危険です。ランサムウェアは、データを暗号化し、データに依存するユーザやアプリケーションがデータを使用できないようにするように設計されています。保護は、強化されたネットワーキングと強固なユーザーセキュリティプラクティスの通常の防御から始まります。そして、データアクセスセキュリティプラクティスに従う必要があります。

ランサムウェアは、今日の最大級のセキュリティ脅威の1つです。NetApp StorageGRIDチームは、これらの脅威に先手を打つためにお客様と協力しています。オブジェクトロックとバージョン管理を使用すると、不要な変更から保護し、悪意のある攻撃からリカバリできます。データセキュリティは多層的な取り組みであり、オブジェクトストレージはデータセンターの一部にすぎません。



== StorageGRIDのベストプラクティス

StorageGRIDのセキュリティのベストプラクティスとして、管理アクセスとオブジェクトアクセスの両方に、署名済み証明書を使用したHTTPSの使用を推奨します。アプリケーションと個人用に専用のユーザアカウントを作成し、アプリケーションアクセスやユーザデータアクセスにテナントrootアカウントを使用しないでください。言い換えれば、最小特権の原則に従ってください。IDおよびアクセス管理（IAM）ポリシーが定義されたセキュリティグループを使用して、ユーザ権限を管理し、アプリケーションおよびユーザに固有のアカウントにアクセスします。これらの対策を実施した場合でも、データを確実に保護する必要があります。Simple Storage Service（S3）では、オブジェクトが暗号化するように変更されると、元のオブジェクトが上書きされます。



== 防御方法

S3 APIの主なランサムウェア対策メカニズムは、オブジェクトロックの実装です。すべてのアプリケーションがオブジェクトロックと互換性があるわけではありません。そのため、このレポートでは、バージョン管理が有効な別のバケットへのレプリケーションと、IAMポリシーによるバージョン管理の2つのオプションについて説明します。



== 追加情報の参照先

このドキュメントに記載されている情報の詳細については、以下のドキュメントや Web サイトを参照してください。

* NetApp StorageGRIDドキュメントセンター https://docs.netapp.com/us-en/storagegrid-118/[]
* NetApp StorageGRIDイネーブルメント https://docs.netapp.com/us-en/storagegrid-enable/[]
* StorageGRIDドキュメントリソースページ https://www.netapp.com/data-storage/storagegrid/documentation/[]
* NetApp製品ドキュメント https://www.netapp.com/support-and-training/documentation/[]

