---
sidebar: sidebar 
permalink: technical-reports/bare-metal-index.html 
keywords: install, storagegrid, deploy, bare metal 
summary: ベアメタルグリッドにStorageGRIDをインストールする方法について説明します。 
---
= StorageGRIDノインストールノガイヨウ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ベアメタルホストにStorageGRIDをインストールする方法について説明します。

TR-4882には、NetApp StorageGRIDの実際的なインストール手順が記載されています。ベアメタルまたはRed Hat Enterprise Linux（RHEL）で実行されている仮想マシン（VM）にインストールできます。このアプローチでは、StorageGRIDコンテナ化された6つのサービスを、推奨されるレイアウトとストレージ構成で、3台の物理（または仮想）マシンに「独自の」インストールを実行します。お客様によっては、このTRに記載されている導入例に従うことで、導入プロセスを理解しやすくなる場合があります。

StorageGRIDとインストールプロセスの詳細については、製品ドキュメントの[Install、upgrade、and hotfix（インストール、アップグレード、およびホットフィックスのStorageGRID）]を参照して https://docs.netapp.com/us-en/storagegrid-118/landing-install-upgrade/index.html[] ください。

展開を開始する前に、NetApp StorageGRID ソフトウェアのコンピューティング、ストレージ、およびネットワークの要件を確認しましょう。StorageGRID は、Podman または Docker 内でコンテナ化されたサービスとして実行されます。このモデルでは、一部の要件はホスト オペレーティング システム（StorageGRID ソフトウェアを実行している Docker をホストする OS）を参照しています。また、リソースの一部は、各ホスト内で実行されている Docker コンテナに直接割り当てられます。今回の導入では、ハードウェアの使用効率を最大化するために、物理ホストごとに 2 つのサービスを導入します。詳細については、次のセクション link:bare-metal-prerequisites-install-storagegrid.html["StorageGRIDをインストールするための前提条件"] に進んでください。

このTRで説明した手順を実行すると、6台のベアメタルホストにStorageGRIDのインストールが完了します。これでグリッドネットワークとクライアントネットワークが正常に機能し、ほとんどのテストシナリオで役立ちます。



[[where-to-find-additional-information]]
== 追加情報の参照先

このTRに記載されている情報の詳細については、次のドキュメントリソースを参照してください。

* NetApp StorageGRIDドキュメントセンター https://docs.netapp.com/us-en/storagegrid-118/[]
* NetApp StorageGRIDイネーブルメント https://docs.netapp.com/us-en/storagegrid-enable/[]
* NetApp製品ドキュメント https://www.netapp.com/support-and-training/documentation/[]

