---
sidebar: sidebar 
permalink: technical-reports/commvault-sizing.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: お客様とNetApp ITによって実装されたStorageGRID構成のユースケースをご紹介します。 
---
= StorageGRIDのサイジングガイダンス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
お客様の環境に合わせた具体的なサイジングについては、NetAppデータ保護のスペシャリストにお問い合わせください。NetAppのデータ保護スペシャリストは、Commvault Total Backup Storage Calculatorツールを使用して、バックアップインフラの要件を見積もることができます。このツールにはCommvaultパートナーポータルへのアクセスが必要です。必要に応じてアクセスにサインアップします。



== Commvaultのサイジング情報

次のタスクを使用して、データ保護解決策のサイジングに関する検出を実行できます。

* 保護が必要なシステムまたはアプリケーション/データベースのワークロードと、対応するフロントエンドの容量（テラバイト[TB]）を特定します。
* 保護が必要なVM /ファイルワークロードと同様のフロントエンド容量（TB）を特定します。
* 短期および長期の保持要件を特定します。
* 特定したデータセット/ワークロードの1日あたりの変更率を特定します。
* 今後12カ月、24カ月、36カ月間のデータ増加予測を特定します。
* ビジネスニーズに応じて、データ保護/リカバリのRTOとRPOを定義します。


この情報が入手可能になったら、バックアップインフラのサイジングを実行し、必要なストレージ容量の内訳を表示できます。



== StorageGRIDのサイジングガイダンス

NetApp StorageGRIDサイジングを実行する前に、ワークロードについて次の点を考慮してください。

* 使用可能容量
* WORMモード
* 平均オブジェクトサイズ
* パフォーマンス要件
* 適用されたILMポリシー


StorageGRIDに階層化したバックアップワークロードのサイズと保持スケジュールに対応するために必要な使用可能容量。

WORMモードは有効になるかどうかCommvaultでWORMを有効にすると、StorageGRIDでオブジェクトロックが設定されます。これにより、必要なオブジェクトストレージ容量が増加します。必要な容量は、保持期間および各バックアップで変更されるオブジェクトの数によって異なります。

平均オブジェクトサイズは、StorageGRID環境でのパフォーマンスのサイジングに役立つ入力パラメータです。Commvaultワークロードに使用される平均オブジェクトサイズは、バックアップのタイプによって異なります。

次の表に、バックアップタイプ別の平均オブジェクトサイズと、リストアプロセスでオブジェクトストアから読み取られる内容を示します。

[cols="1a,1a,1a"]
|===
| バックアップタイプ | 平均オブジェクトサイズ | リストア動作 


 a| 
StorageGRIDで補助コピーを作成する
 a| 
32 MB
 a| 
32MBオブジェクトのフル読み取り



 a| 
バックアップをStorageGRIDに転送する（重複排除が有効）
 a| 
8 MB
 a| 
1MBのランダムレンジ読み取り



 a| 
バックアップをStorageGRIDに転送する（重複排除は無効）
 a| 
32 MB
 a| 
32MBオブジェクトのフル読み取り

|===
また、フルバックアップと増分バックアップのパフォーマンス要件を理解しておくと、StorageGRIDストレージノードのサイズを決定する際に役立ちます。StorageGRIDの情報ライフサイクル管理（ILM）ポリシーのデータ保護方式は、Commvaultバックアップの格納に必要な容量を決定し、グリッドのサイジングに影響します。

StorageGRID ILMレプリケーションは、オブジェクトデータを格納するためにStorageGRIDで使用される2つのメカニズムの1つです。データをレプリケートするILMルールにStorageGRIDがオブジェクトを割り当てると、オブジェクトのデータの完全なコピーが作成されてストレージノードに格納されます。

イレイジャーコーディングは、オブジェクトデータを格納するために StorageGRID で使用される 2 つ目の方法です。イレイジャーコーディングコピーを作成するように設定されたILMルールにStorageGRIDがオブジェクトを割り当てると、オブジェクトデータが複数のデータフラグメントに分割されます。その後、追加のパリティフラグメントを計算し、各フラグメントを別 々 のストレージノードに格納します。アクセスされたオブジェクトは、格納されたフラグメントを使用して再アセンブルされます。データフラグメントまたはパリティフラグメントが破損したり失われたりした場合、イレイジャーコーディングアルゴリズムで残りのデータフラグメントとパリティフラグメントのサブセットを使用してそのフラグメントを再作成できます。

次の例に示すように、2つのメカニズムで必要なストレージ容量は異なります。

* レプリケートコピーを2つ格納すると、ストレージのオーバーヘッドが2倍になります。
* 2+1のイレイジャーコーディングコピーを格納すると、ストレージのオーバーヘッドが1.5倍に増加します。


テストした解決策では、単一サイトのエントリレベルのStorageGRID環境を使用しました。

* 管理ノード：VMware仮想マシン（VM）
* ロードバランサ：VMware VM
* ストレージノード：SG5712（4TBドライブ搭載）×4
* プライマリ管理ノードとゲートウェイノード：本番環境のワークロードの最小要件を満たすVMware VM


[NOTE]
====
StorageGRIDは、サードパーティのロードバランサもサポートしています。

====
StorageGRIDは通常、ノードレベルやサイトレベルの障害から保護するためにデータをレプリケートするデータ保護ポリシーを使用して、2つ以上のサイトに導入されます。データをStorageGRIDにバックアップすることで、複数のコピーまたはイレイジャーコーディングによってデータを保護します。イレイジャーコーディングは、アルゴリズムによってデータを確実に分離して再構成します。

サイジングツールを使用できます。 https://fusion.netapp.com["Fusion"] グリッドのサイズを調整します。



== 拡張性

NetApp StorageGRIDシステムを拡張するには、ストレージノードにストレージを追加するか、既存のサイトに新しいグリッドノードを追加するか、新しいデータセンターサイトを追加します。拡張は現在のシステムの処理を中断せずに実行できます。
StorageGRIDでは、ストレージノードのパフォーマンスが高いノード、またはロードバランサと管理ノードを実行する物理アプライアンスを使用するか、ノードを追加するだけでパフォーマンスを拡張できます。

[NOTE]
====
StorageGRIDシステムの拡張の詳細については、を参照してください https://docs.netapp.com/us-en/storagegrid-119/landing-expand/index.html["StorageGRID 11.9拡張ガイド"]。

====