---
sidebar: sidebar 
permalink: technical-reports/load-balancer-storagegrid.html 
keywords: object storage, load balancer 
summary: StorageGRIDロードバランサーの役割について学習します。 
---
= StorageGRIDロードバランサーを使用する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
StorageGRIDゲートウェイ ノード ロード バランサーの役割について学習します。

NetApp® StorageGRID® ゲートウェイ ノードを実装するための一般的なガイダンス。



== StorageGRIDゲートウェイノードロードバランサと他社製ロードバランサの比較

StorageGRIDは、S3と互換性のあるオブジェクトストレージベンダーの中で唯一、専用のアプライアンス、VM、コンテナとして使用できる標準のロードバランサを提供します。StorageGRIDが提供するロードバランサは、ゲートウェイノードとも呼ばれます。

F5やCitrixなどのロードバランサをまだ所有していないお客様の場合、サードパーティのロードバランサの実装は非常に複雑になる可能性があります。StorageGRIDロードバランサは、ロードバランサの処理を大幅に簡易化します。

ゲートウェイノードは、可用性とパフォーマンスに優れたエンタープライズクラスのロードバランサです。ゲートウェイノード、サードパーティ製ロードバランサ、またはその両方を同じグリッドに実装することもできます。ゲートウェイノードはローカルトラフィックマネージャであり、GSLBではありません。

StorageGRIDロードバランサには、次の利点があります。

* *簡易性*。リソースプール、健全性チェック、パッチ適用、メンテナンスの自動構成をすべてStorageGRIDで管理
* *パフォーマンス*。  StorageGRIDロード バランサはStorageGRID専用であり、高パフォーマンスのキャッシュを提供でき、帯域幅をめぐって他のアプリケーションと競合することはありません。
* *コスト*。仮想マシン（VM）とコンテナのバージョンは追加コストなしで提供されます。
* *トラフィック分類*。高度なトラフィック分類機能を使用すると、StorageGRID固有のQoSルールとワークロード分析を実行できます。
* *今後のStorageGRID固有の機能*。StorageGRIDは、今後のリリースで引き続き最適化を行い、ロードバランサに革新的な機能を追加していきます。


StorageGRIDの統合ノードとして、ローカル トラフィック マネージャーは、高度なヘルス チェックを使用して、ストレージ ノードのヘルス、負荷、およびリソースの可用性に基づいて要求を分散する機能を備えています。さらに、サイト間のStorageGRIDリンク コストが「0」に設定されている場合は、複数のサイトにわたって負荷を分散する機能もあります。ストレージ ノードが使用できないが、サイト内のゲ​​ートウェイ ノードが使用できる場合、負荷はグリッド内の別のサイトに自動的に送信されます。

ゲートウェイ ノードのロード バランサ キャッシュ機能は、データ処理の一環としてデータ セットを複数回再読み取りする特定のワークロード (AI トレーニングなど) のパフォーマンスを大幅に向上させることを目的としています。キャッシュ ゲートウェイ ノードは、グリッドの残りの部分から物理的に離れた場所に展開することも可能で、これにより、一部のワークロードでパフォーマンスが向上し、WAN ネットワークの使用率が低下します。キャッシュはリードバック モードで動作し、書き込みはキャッシュされず、キャッシュの状態は変更されません。各キャッシング ゲートウェイ ノードは、他のキャッシング ゲートウェイ ノードとは独立して動作します。

StorageGRID Gatewayノードの導入の詳細については、 https://docs.netapp.com/us-en/storagegrid/["StorageGRID のドキュメント"^] 。
