---
sidebar: sidebar 
permalink: technical-reports/data-security/index.html 
keywords: security features, storagegrid 
summary: StorageGRIDオブジェクトストレージソリューションに組み込まれているセキュリティ機能をご確認ください。 
---
= オブジェクトストア内のStorageGRIDデータとメタデータを保護
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
StorageGRIDオブジェクトストレージソリューションに組み込まれているセキュリティ機能をご確認ください。

ここでは、データアクセス、オブジェクトとメタデータ、管理アクセス、プラットフォームセキュリティなど、NetApp®StorageGRID®の多数のセキュリティ機能の概要を説明します。StorageGRID 11.9でリリースされた最新機能を含むように更新されています。

セキュリティは、NetApp StorageGRIDオブジェクトストレージソリューションに不可欠な要素です。オブジェクトストレージに適した多くのタイプのリッチコンテンツデータも機密性が高く、規制やコンプライアンスの対象となるため、セキュリティは特に重要です。StorageGRIDの機能が進化し続ける中で、このソフトウェアは、組織のセキュリティ体制を保護し、業界のベストプラクティスに準拠するのに役立つ多くのセキュリティ機能を利用できるようにします。

このホワイトペーパーでは、StorageGRID 11.9のさまざまなセキュリティ機能の概要を5つのカテゴリに分けて説明します。

* データアクセスセキュリティ機能
* オブジェクトとメタデータのセキュリティ機能
* 管理セキュリティ機能
* プラットフォームのセキュリティ機能
* クラウドとの統合


このホワイトペーパーはセキュリティデータシートを目的としています。デフォルトでは設定されていない、に列挙されたセキュリティ機能をサポートするようにシステムを構成する方法については詳しく説明していません。は https://docs.netapp.com/us-en/storagegrid-118/harden/index.html["StorageGRIDセキュリティガイド"^] 公式ページから入手でき https://docs.netapp.com/us-en/storagegrid-118/["StorageGRID のドキュメント"^] ます。

このレポートで説明する機能に加えて、StorageGRIDはにも準拠して https://www.netapp.com/us/legal/vulnerability-response.aspx["NetApp製品セキュリティ脆弱性対応および通知ポリシー"^]います。報告された脆弱性は、製品のセキュリティインシデント対応プロセスに従って検証され、対応されます。

NetApp StorageGRIDは、要件の厳しいエンタープライズオブジェクトストレージのユースケースに対応する高度なセキュリティ機能を提供します。



== 追加情報の参照先

このドキュメントに記載されている情報の詳細については、以下のドキュメントや Web サイトを参照してください。

* NetApp StorageGRID：SEC 17a-4（f）、FINRA 4511（c）、CFTC 1.31（c）-（d）コンプライアンス評価 https://www.netapp.com/media/9041-ar-cohasset-netapp-storagegrid-sec-assessment.pdf[]
* StorageGRID 11.9ドキュメントページ https://docs.netapp.com/us-en/storagegrid-119/[]
* StorageGRIDドキュメントリソースページ https://www.netapp.com/data-storage/storagegrid/documentation/[]
* NetApp製品ドキュメント https://www.netapp.com/support-and-training/documentation/[]




== 用語と略語

このセクションでは、ドキュメントで使用される用語の定義について説明します。

[cols="40,60"]
|===
| 用語または頭字語 | 定義 


| S3 | Simple Storage Serviceの略。 


| クライアント | データアクセス用にS3プロトコルを使用するか、管理用にHTTPプロトコルを使用してStorageGRIDと連携できるアプリケーション。 


| テナント管理者 | StorageGRIDテナントアカウントの管理者 


| テナントユーザ | StorageGRIDテナントアカウント内のユーザ 


| TLS | トランスポート層セキュリティ 


| ILM | 情報ライフサイクル管理 


| LAN | ローカルエリアネットワーク 


| グリッド管理者 | StorageGRIDシステムの管理者 


| グリッド | StorageGRIDシステム 


| バケット | S3に格納されたオブジェクトのコンテナ 


| LDAP | Lightweight Directory Access Protocolの略 


| 秒 | 証券取引委員会（取引所メンバー、ブローカー、ディーラーを規制） 


| フィンラ | 金融業界規制当局（SEC Rule 17a-4（f）のフォーマットおよびメディア要件を延期） 


| CFTC | 商品先物取引委員会、商品先物取引の規制 


| NIST | 米国標準技術研究所 
|===