---
sidebar: sidebar 
permalink: technical-reports/data-security/object-metadata-security.html 
keywords: object metadata security, storagegrid 
summary: StorageGRIDのオブジェクトとメタデータのセキュリティ機能を確認します。 
---
= オブジェクトとメタデータのセキュリティ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
StorageGRIDのオブジェクトとメタデータのセキュリティ機能を確認します。

[cols="20,30a,30,20"]
|===
| 機能 | 機能 | 影響 | コンプライアンス 


| Advanced Encryption Standard（AES）サーバ側オブジェクト暗号化  a| 
StorageGRIDは、AES 128およびAES 256ベースのサーバ側オブジェクト暗号化を提供します。グリッド管理者は、暗号化をグローバルなデフォルト設定として有効にすることができます。StorageGRIDはS3のx-amz-server-side-encryptionヘッダーもサポートしており、オブジェクト単位で暗号化を有効または無効にできます。有効にすると、グリッドノード間で格納または転送中のオブジェクトが暗号化されます。
| 基盤となるストレージハードウェアに依存せずに、ストレージやオブジェクトの転送を保護します。 | SECルール17a-4（f）CTFC 1.31（c）-（d）（FINRA）ルール4511（c） 


| 組み込みのキー管理機能  a| 
暗号化を有効にすると、各オブジェクトがランダムに生成された一意の対称キーで暗号化され、外部アクセスなしでStorageGRID内に格納されます。
| 外部キー管理を必要とせずにオブジェクトを暗号化できます。 |  


| Federal Information Processing Standard（FIPS）140-2準拠の暗号化ディスク  a| 
SG5712、SG5760、SG6060、およびSGF6024 StorageGRIDアプライアンスには、FIPS 140-2準拠の暗号化ディスクをオプションで選択できます。必要に応じて、外部KMIPサーバでディスクの暗号化キーを管理できます。
| システムデータ、メタデータ、オブジェクトのセキュアなストレージを実現します。また、StorageGRIDソフトウェアベースのオブジェクト暗号化を提供し、オブジェクトのストレージと転送を保護します。 | SECルール17a-4（f）CTFC 1.31（c）-（d）（FINRA）ルール4511（c） 


| バックグラウンド整合性スキャンと自己回復  a| 
StorageGRIDでは、オブジェクトレベルとサブオブジェクトレベルでハッシュ、チェックサム、巡回冗長検査（CRC）のインターロックメカニズムを使用して、オブジェクトが格納中と転送中の両方でデータの不整合、改ざん、変更から保護します。StorageGRIDは、破損したオブジェクトや改ざんされたオブジェクトを自動的に検出して置換し、変更されたデータを隔離して管理者に警告します。
| グリッド管理者は、SLA、規制、データ保持に関するその他の義務を満たすことができます。データの暗号化、改ざん、変更を試みるランサムウェアやウイルスの検出を支援します。 | SECルール17a-4（f）CTFC 1.31（c）-（d）（FINRA）ルール4511（c） 


| ポリシーベースのオブジェクトの配置と保持  a| 
StorageGRIDを使用すると、グリッド管理者はILMルールを設定して、オブジェクトの保持、配置、保護、移行、有効期限を指定できます。グリッド管理者はStorageGRID、メタデータでオブジェクトをフィルタリングし、グリッド全体、テナント、バケット、キープレフィックス、 およびユーザ定義のメタデータのキーと値のペア。StorageGRIDを使用すると、クライアントによって明示的に削除されないかぎり、ライフサイクル全体を通じてオブジェクトがILMルールに従って格納されるようになります。
| データの配置、保護、保持を徹底データ保持性、可用性、パフォーマンスに関するSLAの達成を支援 | SECルール17a-4（f）CTFC 1.31（c）-（d）（FINRA）ルール4511（c） 


| バックグラウンドメタデータスキャン  a| 
StorageGRIDは、オブジェクトメタデータをバックグラウンドで定期的にスキャンし、オブジェクトデータの配置または保護の変更をILMの指定に従って適用します。
| 破損したオブジェクトの検出に役立ちます。 |  


| 調整可能な整合性  a| 
テナントはバケットレベルで整合性レベルを選択して、マルチサイト接続などのリソースを利用できるようにすることができます。
| 必要な数のサイトまたはリソースが使用可能な場合にのみ、グリッドへの書き込みをコミットするオプションを提供します。 |  
|===