---
sidebar: sidebar 
permalink: technical-reports/commvault/index.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: お客様とNetApp ITによって実装されたStorageGRID構成のユースケースをご紹介します。 
---
= StorageGRIDとCommvaultを使用したデータのバックアップとリカバリ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
CommvaultとNetAppは提携して、Commvault Complete Backup and Recovery for NetAppソフトウェアとクラウドストレージ向けのNetApp StorageGRIDソフトウェアを組み合わせた共同データ保護解決策を作成しました。Commvault Complete Backup and RecoveryとNetApp StorageGRIDは、相互に連携して機能する独自の使いやすいソリューションを提供し、急速なデータ量の増大や世界各地の規制への対応を支援します。

多くの組織は、ストレージをクラウドに移行し、システムを拡張し、データの長期保持に関するポリシーを自動化したいと考えています。クラウドベースのオブジェクトストレージは、耐障害性、拡張性、運用効率とコスト効率に優れていることで知られており、バックアップのターゲットとして最適です。CommvaultとNetAppは、2014年に解決策の統合を共同で認定し、それ以来、両社のソリューション間の緊密な統合を設計してきました。世界中のあらゆるタイプのお客様が、Commvault Complete Backup and RecoveryとStorageGRID Combined解決策を採用しています。



== CommvaultとStorageGRIDについて

Commvault Complete Backup and Recoveryソフトウェアは、エンタープライズレベルの統合データおよび情報管理解決策で、単一プラットフォーム上に一から構築され、統合コードベースを備えています。すべての機能がバックエンドテクノロジを共有し、データの保護、管理、アクセスに完全に統合されたアプローチによる比類のないメリットとメリットをもたらします。このソフトウェアには、データを保護、アーカイブ、分析、複製、検索するためのモジュールが含まれています。これらのモジュールは、相互にシームレスに連携する、共通のバックエンドサービスと高度な機能セットを共有しています。解決策は、企業のデータ管理のあらゆる側面に対応しながら、無限の拡張性とかつてないデータと情報の制御を提供します。

Commvaultクラウド階層としてのNetApp StorageGRIDは、エンタープライズハイブリッドクラウドのオブジェクトストレージ解決策です。専用アプライアンスまたはSoftware-Defined環境のいずれかを使用して、多数のサイトに導入できます。StorageGRIDを使用すると、データの格納方法と保護方法を決定するデータ管理ポリシーを確立できます。StorageGRIDは、ポリシーの開発と実施に必要な情報を収集します。パフォーマンス、耐久性、可用性、地理的な場所、 長寿とコスト。データは、サイト間や古くなっても、完全に維持され、保護されます。

StorageGRIDインテリジェントポリシーエンジンを使用すると、次のいずれかのオプションを選択できます。

* イレイジャーコーディングを使用して複数のサイトにデータをバックアップし、耐障害性を確保するため。
* オブジェクトをリモートサイトにコピーしてWANのレイテンシとコストを最小限に抑えること。


StorageGRIDにオブジェクトが格納されると、その場所やコピーの数に関係なく、オブジェクトに1つのオブジェクトとしてアクセスできます。この動作はディザスタリカバリに不可欠です。ディザスタリカバリでは、データの1つのバックアップコピーが破損しても、StorageGRIDはデータをリストアできます。

バックアップデータをプライマリストレージに保持すると、コストがかかる場合があります。NetApp StorageGRIDを使用すると、使用頻度の低いバックアップデータをStorageGRIDに移行してプライマリストレージのスペースを解放しながら、StorageGRIDのさまざまな機能を活用できます。バックアップデータの価値は時間の経過とともに変化し、保存コストも変化します。StorageGRIDを使用すると、データの保持性を高めながら、プライマリストレージのコストを最小限に抑えることができます。



== 主な特長

Commvaultソフトウェアプラットフォームの主な機能は次のとおりです。

* 仮想サーバと物理サーバ、NASシステム、クラウドベースのインフラ、モバイルデバイス上のすべての主要なオペレーティングシステム、アプリケーション、データベースをサポートする完全なデータ保護解決策。
* 単一のコンソールによるシンプルな管理：企業全体のすべての機能とすべてのデータと情報を表示、管理、アクセスできます。
* データのバックアップとアーカイブ、Snapshot管理、データレプリケーション、eディスカバリ向けのコンテンツインデックス作成など、さまざまな保護方法が用意されています。
* ディスクストレージとクラウドストレージの重複排除による効率的なストレージ管理
* AFF、FAS、NetApp HCI、Eシリーズアレイ、NetApp SolidFire ^®^スケールアウトストレージシステムなどのNetAppストレージアレイとの統合また、NetApp Cloud Volumes ONTAPソフトウェアとの統合により、NetAppストレージポートフォリオ全体で、インデックス付きのアプリケーション対応NetApp Snapshot™コピーの作成を自動化できます。
* 業界をリードするオンプレミスの仮想ハイパーバイザーとパブリッククラウドハイパースケーラプラットフォームをサポートする包括的な仮想インフラ管理
* 重要なデータへのアクセスを制限し、きめ細かな管理機能を提供し、Active Directoryユーザにシングルサインオンアクセスを提供する高度なセキュリティ機能。
* ポリシーベースのデータ管理により、物理的な場所ではなく、ビジネスニーズに基づいてデータを管理できます。
* 最先端のエンドユーザエクスペリエンスで、ユーザが自身のデータを保護、検索、リカバリできるようにします。
* APIベースの自動化：vRealize AutomationやService Nowなどのサードパーティ製ツールを使用してデータ保護とリカバリの処理を管理できます。


サポートされるワークロードの詳細については、を参照してください https://www.commvault.com/supported-technologies["Commvaultがサポートするテクノロジ"]。



== バックアップオプション

Commvault Complete Backup and Recoveryソフトウェアをクラウドストレージに実装する場合は、次の2つのバックアップオプションがあります。

* プライマリディスクターゲットにバックアップし、補助コピーをクラウドストレージにバックアップします。
* プライマリターゲットとしてクラウドストレージにバックアップします。


これまで、クラウドやオブジェクトストレージは、プライマリバックアップに使用するにはパフォーマンスが低すぎると考えられていました。プライマリディスクターゲットを使用することで、バックアップとリストアのプロセスを高速化し、コールドバックアップとしてクラウドに補助コピーを保持することができました。StorageGRIDは次世代のオブジェクトストレージです。StorageGRIDは、他のオブジェクトストレージベンダーが提供するよりも優れたパフォーマンスと優れたスループットに加え、優れたパフォーマンスと柔軟性を備えています。

次の表に、StorageGRIDを使用した各バックアップオプションの利点を示します。

[cols="1a,1a,1a"]
|===
|  | ディスクへのプライマリ・バックアップとStorageGRIDへの補助コピー | StorageGRIDへのプライマリバックアップ 


 a| 
パフォーマンス
 a| 
ライブマウントまたはライブリカバリを使用した最速のリカバリ時間：Tier0/Tier1ワークロードに最適
 a| 
ライブマウントまたはライブリカバリ処理には使用できません。ストリーミングリストア処理や長期保持に最適です。



 a| 
導入アーキテクチャ
 a| 
オールフラッシュまたは回転式ディスクを第1のバックアップランディング層として使用StorageGRIDはセカンダリ階層として使用されます。
 a| 
包括的なバックアップターゲットとしてStorageGRIDを使用することで、導入を簡易化します。



 a| 
高度な機能（ライブリストア）
 a| 
サポートされます
 a| 
サポート対象外

|===


== 追加情報の参照先

このドキュメントに記載されている情報の詳細については、以下のドキュメントや Web サイトを参照してください。

* StorageGRID 11.8ドキュメントセンター+
https://docs.netapp.com/us-en/storagegrid-118/[]
* NetApp製品ドキュメント+
https://docs.netapp.com[]
* Commvaultのドキュメント+
https://documentation.commvault.com/2024/essential/index.html[]

